# conda env create -f environment.yml
name: lcls-live
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib-base
  - pandas
  - requests
  - pyepics
  - pyyaml
  - pytao
  - bmad
  - openpmd-beamphysics  
  - ipywidgets
  - jupyterlab
  - pip
# Developer
#  - pip:
#    - git+git://github.com/slaclab/lcls-live
